name: Recent Activity
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    permissions:
        contents: write
        
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
